export const exploreDatas = [
  {
    id: 1,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
  {
    id: 2,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
  {
    id: 3,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
  {
    id: 4,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
  {
    id: 5,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
  {
    id: 6,
    title: "Just Cut CNX",
    image: "https://placehold.jp/164x164.png",
    openTime: "9:30 AM",
    closeTime: "17:30 PM",
    location: "Nimmanhaemin Road Chiangmai Thailand",
    contact: "091-234-5678",
    detail: `Welcome to "Just Cut.", where style meets comfort in every snip! Located in a cozy corner of town, our warm and inviting atmosphere greets you the moment you step through the door. With soft, plush seating and soothing music playing in the background, we've created the perfect oasis for your hair care needs.`,
  },
];
